---
title: "Gov 50 Final Project"
author: "Siri Panetta"
description: "My Final Project"
output:
  distill::distill_article:
    self_contained: false
---



## Project Thoughts

Milestone 2: 
How does median income affect a town’s political views? I hypothesize that the more wealthy areas will be more conservative. People with more money are more likely to support tax cuts for the wealthy and less social programs, which are in-line with Republican party views. People with less money are more likely to want more funding allocated to social programs and more taxes on the wealthy, which is more in-line with Democratic party views. My sample consists of data on around 10,000 towns across America. My unit of analysis is a single town. My explanatory variable is income1990, which is the median income in 1990 for each town surveyed. Another possible explanatory variable that may come in useful is logincome1990, which is the median income in 1990 for each town surveyed but on the logarithmic scale. I have two choices for my outcome variable of interest. One is gopvoteshare1992, which is the two-party vote share for the Republicans in the 1992 presidential election. The other variable is gopvoteshare2000, which is the two-party vote share for the Republicans in the 2000 presidential election. The 1992 election is closer to when the data on median income was taken, but the 2000 election is closer to current times. If I observe that towns with higher median incomes also have higher vote shares for Republicans (direct relationship), then my hypothesis will be proven. However, if I observe that towns with higher median incomes have lower vote shares for Republicans (inverse relationship), then my hypothesis will be disproved. 

Milestone 1:
I am interested in exploring data related to the sleep of Harvard freshmen. Many first-year students have not mastered their study patterns, so I am interested in how much sleep they get, when they go to bed, when they wake up, what their intended concentration is, what their gender is, how many clubs they are part of, what dorm they are in, and other identifying information. I would plan to collect this data msyelf through some means (personal surveys or possibly through social media). If this does not work, I am also interested in where Harvard freshmen study and how that possibly relates to their intended concentration, dorm, gender, etc..

